### PR TITLE
Fix for constant folding of null tuple/slice/builder/cell types

### PR DESCRIPTION
**Pull request by azhogin**
Supported null tuple/slice/builder/cell.
Part of C++ support patch.

### CODE REVIEW

**Comment by mskvortsov** [comment]
It looks like there is a contradiction regarding null values:
```
; CHECK-LABEL: null_slice_intr:
define slice @null_slice_intr() {
; CHECK: PUSHNULL
  %s = call slice @llvm.tvm.cast.to.slice(i257 0)
  ret slice %s
}
; CHECK-LABEL: slice_intr:
define slice @slice_intr(i257 %v) {
  %s = call slice @llvm.tvm.cast.to.slice(i257 %v)
  ret slice %s
}
; CHECK-LABEL: zero_slice_intr:
define slice @zero_slice_intr() {
; CHECK: PUSHINT 0
  %s = call slice @slice_intr(i257 0)
  ret slice %s
}
declare slice @llvm.tvm.cast.to.slice(i257 %v)
```
Shouldn't the effects of calling `zero_slice_intr` and `null_slice_intr` be the same?

**Comment by azhogin** [comment]
> Shouldn't the effects of calling zero_slice_intr and null_slice_intr be the same?

I don't think so.
Dynamic value, provided into some function as i257 should be created as PUSHINT.
If inside the called function you convert dynamic value into slice - you should understand why.
This patch was added just for NULL tuple/slice/builder/cell initialization.
Mostly for cases like:
```
class cell {
public:
  bool is_null() const { return __builtin_tvm_isnull(val_); }
private:
  __tvm_cell val_;
};
```
Probably, we can add intrinsics for explicit creation of null tuple/slice/builder/cell later to eliminate implicit behaviour.
```
class cell {
public:
  cell() : val_(__builtin_tvm_nullcell()) {}
  bool is_null() const { return __builtin_tvm_isnull(val_); }
private:
  __tvm_cell val_;
};
```

**Comment by mskvortsov** [comment]
On the one hand, I understand the demand behind this change, and PR #66 dependent on it would be very useful for my own task actually.

On the other hand, nobody likes temporary solutions, especially those which introduce subtle bugs. Like depending on whether something was inlined or not, the compiler generates different code producing values of different types on a stack.

(And I'm not sure the concept of dynamic values is applicable to the LLVM's type system at all. It will be hard to justify the issue in these terms to an ordinary LLVM user.)

**Comment by azhogin** [comment]
> 
Added __builtin_tvm_pushnull builtin & intrinsic. Removed bitcast folding from 0.

**Pull request merged**
